[mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
ignore_missing_imports = true
disable_error_code = attr-defined,return-value,override,typeddict-item,dict-item,assignment,arg-type,union-attr
