blank_issues_enabled: false
contact_links:
  - name: Bosch SHC Local API Docs
    url: https://github.com/BoschSmartHome/bosch-shc-api-docs
    about: Official Bosch Smart Home Controller local REST API documentation.
