name: Dependency review

on:
  pull_request:
    paths:
      - "requirements*.txt"
      - "custom_components/bosch_shc/manifest.json"
      - "pyproject.toml"
      - "setup.py"

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5.0.1
      - uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48  # v4.9.0
        with:
          fail-on-severity: high
